spring.application.name=kanban
spring.datasource.url=${KANBAN_DB_URL}
spring.datasource.username=${KANBAN_DB_USER}
spring.datasource.password=${KANBAN_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
